version: "2.0"
services:
    php:
        build:
            context: ./
            dockerfile: dockerfile
        container_name: apache-server
        restart: always
        ports:
            - 80:80
        volumes: 
            - ./:/var/www/html
volumes:
    html: {}